import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/shared/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <head>
            <title>Portal</title>
          </head>
          <ClerkProvider>
              <body
                className={`antialiased`}
              >
              <SidebarProvider>
                <AppSidebar/>
                {/* <Topbar/> */}
                <SidebarTrigger/>
                {children}
             </SidebarProvider>
              </body>
            </ClerkProvider>
        </html>
  );
}
