import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/shared/Sidebar";
import { getUser, isVerrified } from "@/lib/actions/user.actions";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
  {
    const user = await currentUser();
    if(!user){
      redirect('/sign-in');
    }
    
    const monUser : any = await getUser({id : user.id});
    if(!monUser || !monUser.onboarded){
      redirect('/onboarding')
      return null
    }
    const verrified = await isVerrified({id : user.id});
    return (
        <html lang="en">
          <head>
            <title>Portal</title>
          </head>
          <ClerkProvider>
          { verrified ?
          (
              
              <body
                className={`antialiased`}
              >
              <SidebarProvider>
                <AppSidebar/>
                {/* <Topbar/> */}
                <SidebarTrigger/>
                {children}
             </SidebarProvider>
              </body>
            ) :           
            (<body>
              <div className="m-5 fixed flex">
                <UserButton></UserButton>
                <h1>Current Account</h1>
              </div>
              <div className="w-100 h-screen flex justify-center items-center">
                <h1 className="text-red-400 text-5xl">Awating verification </h1>
              </div>

          </body>)
          }
          </ClerkProvider>
        </html>
  );
}
