import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/shared/sidebar/Sidebar";
import { getUser, isVerrified } from "@/lib/actions/user.actions";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import Verification from "../components/shared/Verification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
  {
    const user = await currentUser();
    if(!user){
      redirect('/sign-in');
    }
    
    const monUser : any = await getUser({id : user.id});
    if(!monUser || !monUser.onboarded){
      redirect('/onboarding')
      return null
    }
    
    const verrified = monUser.verified;

    return (
        <html lang="en">
          <head>
            <title>Portal</title>
          </head>
          <ClerkProvider>
          { verrified ?
          (
              
              <body
                className={`antialiased`}
              >
              <SidebarProvider>
                <AppSidebar/>
                {/* <Topbar/> */}
                <SidebarTrigger/>
                {children}
             </SidebarProvider>
              </body>
            ) :           
            (<Verification/>)
          }
          </ClerkProvider>
        </html>
  );
}
